apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  type: NodePort
  selector:
    type: gitlab
  ports:
    - protocol: "TCP"
      name: "http"
      port: 80
      nodePort: 30080
    - protocol: "TCP"
      name: "ssh"
      port: 22
      nodePort: 30022
