apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab-controller
spec:
  replicas: 1
  selector:
    type: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        type: gitlab
    spec:
      containers:
        - name: gitlab
          image: sameersbn/gitlab:8.2.1-1
          env:
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: gitlab
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: gitlabhq_production
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: GITLAB_PORT
              value: "30080"
            - name: GITLAB_SSH_PORT
              value: "30022"
            - name: GITLAB_SECRETS_DB_KEY_BASE
              value: "FNxRbFFtvcmVvSdhSFg63GFxLNTb227p4WphT5DMpCSMFWJrxKGgkMvsWjs9dh2X"
            - name: GITLAB_ROOT_PASSWORD
              value: wkeiscool
          ports:
            - containerPort: 22
            - containerPort: 80
          livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 90
              timeoutSeconds: 5
