apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-controller
spec:
  replicas: 1
  selector:
    type: redis
  template:
    metadata:
      name: redis
      labels:
        type: redis
    spec:
      containers:
        - name: redisio
          image: sameersbn/redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /var/lib/redis
              name: redis-data
      volumes:
        - name: redis-data
          hostPath:
            path: "/tmp/redis"
