apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    game: starwars
    player: wescale
spec:
  containers:
    - name: sw
      image: tutum/hello-world
      ports:
        - name: www
          containerPort: 80
