apiVersion: v1
kind: ReplicationController
metadata:
  name: sw-controller
spec:
  replicas: 10
  selector:
    game: starwars
    player: cedric
  template:
    metadata:
      name: hello
      labels:
        game: starwars
        player: cedric
    spec:
      containers:
        - name: sw
          image: tutum/hello-world
          ports:
            - name: www
              containerPort: 80
